# Generated by Django 6.0.3 on 2026-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
